apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: web
        image: karthikpreddy/gitops-demo-app:9e5868094bb3ceff4a6d6870fee0e999aa19c8d0
        imagePullPolicy: Always   # <--- ADD THIS LINE 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app
  namespace: default
spec:
  selector:
    app: gitops-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
