apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-demo-app
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: app.gitops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitops-demo-app
            port:
              number: 80
  tls:
  - hosts:
    - app.gitops.local
    secretName: demo-app-tls
